//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "article_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub article_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "article_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub articles: HasOne<super::articles::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tags: HasOne<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
