//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "articles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub slug: String,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub author_id: Uuid,
    #[sea_orm(belongs_to, from="author_id", to="id", relation_enum="Author" )]
    pub author: HasOne<super::users::Entity>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub comments: HasMany<super::comments::Entity>,
    #[sea_orm(has_many, via = "article_tags")]
    pub tags: HasMany<super::tags::Entity>,

    #[sea_orm(has_many)]
    pub article_tags: HasMany<super::article_tags::Entity>,

    #[sea_orm(has_many)]
    pub article_favorites: HasMany<super::article_favorites::Entity>,

    #[sea_orm(has_many, via = "article_favorites")]
    pub users: HasMany<super::users::Entity>,


    //#[sea_orm(has_many, from="author_id", to="followee_id", relation_enum="Auth")]
    //pub user_follows: HasMany<super::user_follows::Entity>,

}


impl ActiveModelBehavior for ActiveModel {}


