//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod article_favorites;
pub mod article_tags;
pub mod articles;
pub mod comments;
pub mod tags;
pub mod user_follows;
pub mod users;
