//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::article_favorites::Entity as ArticleFavorites;
pub use super::article_tags::Entity as ArticleTags;
pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::tags::Entity as Tags;
pub use super::user_follows::Entity as UserFollows;
pub use super::users::Entity as Users;
