//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_follows")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub follower_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub followee_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "followee_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users_2: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "follower_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users_1: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
